sudo: false
git:
  depth: 1

language: c

#compiler:
#  - gcc
#  - clang

script:
  - cd platforms
  - sh build.sh

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libsdl2-dev
    - os: osx
      before_install:
        - brew install sdl2
